### PR TITLE
Try building on Windows

### LINKED ISSUE #13: Windows support?
Is there a reason not to include Windows support in the conda-forge unzip recipe?

Looking over http://infozip.sourceforge.net/UnZip.html suggests it should work.

### PR DESCRIPTION
**Pull request by peterjc**
This aims to close #13 

We might have to switch to using win32/Makefile.gcc but that suggests can use unix/Makefile to get a POSIX build. If we do switch, will have to implement a Windows install.

Note the upstream FTP site is rather slow, but worked in Firefox:

ftp://ftp.info-zip.org/pub/infozip/src/unzip60.tgz

May need to switch to using SourceForge instead:

https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz

Same file but different extension.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by peterjc** [comment]
Looks like additional magic is needed to run the tests under Windows... guessing the rerender will do that.

**Comment by peterjc** [comment]
Can also try ``make -f win32/Makefile ...`` for MSVC++ although comments say it was only used on v2.

Correction:

```
# Tested with VC++ 2.0 for NT for MIPS and Alpha, Visual C++ 2.2 for Intel CPUs
# Revision tested with VC++ 5.0, 6.0, 8.0 and 9.0 for Intel CPUs
```

**Comment by peterjc** [comment]
OK, the naive approach failed - almost to be expected:

```
[vcvarsall.bat] Environment initialized for: 'x64'
mkdir -p REFIX/bin
cp unzip funzip unzipsfx REFIX/bin
cp: cannot stat 'unzip': No such file or directory
cp: cannot stat 'funzip': No such file or directory
cp: cannot stat 'unzipsfx': No such file or directory
make: *** [unix/Makefile:452: install] Error 1
```

Next, Plan B, explicitly using ``make -f win32/Makefile ... `` and the MS compiler.

**Comment by peterjc** [comment]
Ignoring the TravisCI failure, looks like it was a network outage.

Windows failed:

```
win32/Makefile:47: *** missing separator.  Stop.
Invalid number of parameters
```

That is the line ``!IFNDEF debug`` in the following:

```
# Nmake macros for building Win32 applications
# To build with debug info use 'nmake debug=1'
!IFNDEF debug
NODEBUG=1
!ENDIF
```

**Comment by peterjc** [comment]
Progress - it started to compile!

```

ubz2err.c
	cl -O2 -c -W3 -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_X86_=1  -DWIN32 -D_WIN32 -nologo -J -D_MBCS -DASM_CRC -DIZ_CRCOPTIM_UNFOLDTBL -DUNICODE_SUPPORT  -Founreduce.obj unreduce.c
unreduce.c
	cl -O2 -c -W3 -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_X86_=1  -DWIN32 -D_WIN32 -nologo -J -D_MBCS -DASM_CRC -DIZ_CRCOPTIM_UNFOLDTBL -DUNICODE_SUPPORT  -Founshrink.obj unshrink.c
unshrink.c
	cl -O2 -c -W3 -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_X86_=1  -DWIN32 -D_WIN32 -nologo -J -D_MBCS -DASM_CRC -DIZ_CRCOPTIM_UNFOLDTBL -DUNICODE_SUPPORT  -Fozipinfo.obj zipinfo.c
zipinfo.c
zipinfo.c(1585): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
zipinfo.c(1594): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
	cl -O2 -c -W3 -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_X86_=1  -DWIN32 -D_WIN32 -nologo -J -D_MBCS -DASM_CRC -DIZ_CRCOPTIM_UNFOLDTBL -DUNICODE_SUPPORT  -I. win32/win32.c -Fowin32.obj
win32.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18496): error C2143: syntax error: missing ':' before 'constant'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18496): error C2143: syntax error: missing ';' before ':'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18496): error C2059: syntax error: ':'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18497): error C2143: syntax error: missing '{' before ':'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18497): error C2059: syntax error: ':'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18498): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18499): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(18500): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\stralign.h(120): warning C4090: 'function': different '__unaligned' qualifiers
win32/win32.c(497): warning C4996: 'GetVersion': was declared deprecated
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\sysinfoapi.h(135): note: see declaration of 'GetVersion'
win32/win32.c(1526): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
win32/win32.c(1684): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
win32/win32.c(2411): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
Invalid number of parameters
```

Lots to type conversion warnings. The apparent list of syntax errors in ``C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h`` the problem.

**Comment by peterjc** [comment]
This was uncannily similar:
https://stackoverflow.com/questions/58751720/compiler-errors-in-winnt-h-after-retargeting-solution-to-latest-sdk-10-0-18362

Pointed me here, where unzip was actually listed as a test case for this:
https://developercommunity.visualstudio.com/t/visual-studio-2019-1622-error-c2143c2059-in-winnth/699469

And indeed, ``unzpriv.h`` defines ``CR`` which clashes:

```
#define CR     13        /* '\r' on ASCII machines; must be 13 due to EBCDIC */
```

Probably need a patch to change that ``CR`` macro to something longer like ``CARRIAGE_RETURN`` here and in at least ``fileio.c`` and ``unzpriv.h`` and ``win32/w32cfg.h``:

```
$ grep "[^a-zA-Z_]CR[^a-zA-Z_]" *.c *.h win32/*.c win32/*.h
api.c:                          characters other than CR, LF, or tab in the first
fileio.c:        Algorithm:  CR/LF => native; lone CR => native; lone LF => native.
fileio.c:                if (*p == CR) {           /* lone CR or CR/LF: treat as EOL  */
fileio.c:             * (since used before A_TO_N(), check for CR instead of '\r')
fileio.c:                while (*p == CR)
fileio.c:                    else if (p[1] == CR && p[2] == LF) {  /* ASCII CR LF */
process.c:    Open the zipfile for reading in BINARY mode to prevent CR/LF translation,
ttyio.c:                c = '\n';       /* until user hits CR */
unzpriv.h:#  define PutNativeEOL  {*q++ = native(CR); *q++ = native(LF);}
unzpriv.h:#  include <fcntl.h>          /* O_BINARY for open() w/o CR/LF translation */
unzpriv.h:#  define PutNativeEOL    {*q++ = native(CR); *q++ = native(LF);}
unzpriv.h:#define CR     13        /* '\r' on ASCII machines; must be 13 due to EBCDIC */
win32/win32.c: * (Under Win95, ENTER returns two(!!) characters: CR-LF.)  This problem
win32/win32.c:  /* when the user hits return we get CR LF.  We discard the LF, not the CR,
win32/w32cfg.h:#define PutNativeEOL  {*q++ = native(CR); *q++ = native(LF);}
```

**Comment by peterjc** [comment]
Progress, fails later:

```

	rc /l 0x409 /fowinapp.res /i win32 /d WIN32 win32/winapp.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.


	link /RELEASE /INCREMENTAL:NO /PDB:NONE /NOLOGO /subsystem:console kernel32.lib  advapi32.lib user32.lib   unzip.obj crc32.obj crc_i386.obj crypt.obj envargs.obj explode.obj extract.obj fileio.obj globals.obj inflate.obj list.obj match.obj process.obj ttyio.obj ubz2err.obj unreduce.obj unshrink.obj zipinfo.obj win32.obj win32i64.obj nt.obj winapp.res -out:unzip.exe
extract.obj : error LNK2019: unresolved external symbol crc32 referenced in function TestExtraField
fileio.obj : error LNK2001: unresolved external symbol crc32
process.obj : error LNK2001: unresolved external symbol crc32
nt.obj : error LNK2019: unresolved external symbol InterlockedExchange referenced in function Initialize
unzip.exe : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
Invalid number of parameters
```

Looks like ``winnt.h`` would define ``InterlockedExchange`` but I'm unclear how/where that is being used.
https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedexchange

There are several options for the crc32 code...

**Comment by peterjc** [comment]
MASM didn't work,

```
	masm -ml win32/crc_i386.asm,crc_i386.obj;
'masm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by peterjc** [comment]
Progress, that solved the crc32 problem:

```

	link /RELEASE /INCREMENTAL:NO /PDB:NONE /NOLOGO /subsystem:console kernel32.lib  advapi32.lib user32.lib   unzip.obj crc32.obj crypt.obj envargs.obj explode.obj extract.obj fileio.obj globals.obj inflate.obj list.obj match.obj process.obj ttyio.obj ubz2err.obj unreduce.obj unshrink.obj zipinfo.obj win32.obj win32i64.obj nt.obj winapp.res -out:unzip.exe
nt.obj : error LNK2019: unresolved external symbol InterlockedExchange referenced in function Initialize
unzip.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
```

This could be a missing header...

**Comment by peterjc** [comment]
Nope. And reading https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedexchange says:

```
Header winnt.h (include Windows.h)
```

But the source already has ``#include <windows.h>`` lines...

**Comment by peterjc** [comment]
@conda-forge/help-c-cpp is there anything you can suggest for this Windows specific linking problem with nmake and MSCV?

```
	link /RELEASE /INCREMENTAL:NO /PDB:NONE /NOLOGO /subsystem:console kernel32.lib  advapi32.lib user32.lib   unzip.obj crc32.obj crypt.obj envargs.obj explode.obj extract.obj fileio.obj globals.obj inflate.obj list.obj match.obj process.obj ttyio.obj ubz2err.obj unreduce.obj unshrink.obj zipinfo.obj win32.obj win32i64.obj nt.obj winapp.res -out:unzip.exe
nt.obj : error LNK2019: unresolved external symbol InterlockedExchange referenced in function Initialize
unzip.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
```

Thanks!

**Comment by peterjc** [comment]
Interesting, inserting ``include <windows.h>`` into ``win32/w32cfg.h`` made it fail earlier:

```
cl -O2 -c -W3 -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_X86_=1  -DWIN32 -D_WIN32 -nologo -J -D_MBCS -DNO_ASM -DIZ_CRCOPTIM_UNFOLDTBL -DUNICODE_SUPPORT  -Founzip.obj unzip.c
unzip.c
d:\bld\unzip_1619089590264\work\win32/w32cfg.h(140): error C2143: syntax error: missing '{' before '<'
d:\bld\unzip_1619089590264\work\win32/w32cfg.h(140): error C2059: syntax error: '<'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\excpt.h(49): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(1382): error C2143: syntax error: missing '{' before '__cdecl'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(1390): error C2143: syntax error: missing '{' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(11379): error C2061: syntax error: identifier 'PEXCEPTION_ROUTINE'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(11380): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(11382): error C2143: syntax error: missing '{' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\stralign.h(120): warning C4090: 'function': different '__unaligned' qualifiers
unzip.c(1185): warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data
unzip.c(1189): warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data
unzip.c(1207): warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data
unzip.c(1223): warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data
unzip.c(1227): warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
```

Probably introduced another clashing define.

**Comment by peterjc** [comment]
Gave up on the MS compiler, next plan - MingW

@conda-forge-admin, please rerender

**Comment by peterjc** [comment]
Hmm. Failure,

```
(%BUILD_PREFIX%) %SRC_DIR%>make -f win32/Makefile.gcc CC=$CC prefix="$PREFIX" CF="$CFLAGS -I." LFLAGS1="$LDFLAGS" NOASM=1 
C -c -DWIN32 -DFORCE_WIN32_OVER_UNIX  -Wall -DIZ_CRCOPTIM_UNFOLDTBL  -o unzip.o  -O2 -mcpu=pentiumpro unzip.c
process_begin: CreateProcess(NULL, C -c -DWIN32 -DFORCE_WIN32_OVER_UNIX -Wall -DIZ_CRCOPTIM_UNFOLDTBL -o unzip.o -O2 -mcpu=pentiumpro unzip.c, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [win32/Makefile.gcc:294: unzip.o] Error 2
```

These are lines 942 through 296 (i.e. middle one is line 294) of ``win32/Makefile.gcc``:

```
# How to compile sources
.c$(OBJ):
        $(CC) $(CFLAGS) $(CVER) $(GENFLAGS) $<
.S$(OBJ):
        $(AS) $(ASFLAGS) $(ASVER) $(GENFLAGS) $<
```

**Comment by peterjc** [comment]
Didn't really expect it to, but forcing ``USE_POSIX=1`` mode didn't help:

```
(%BUILD_PREFIX%) %SRC_DIR%>make -f win32/Makefile.gcc CC=$CC prefix="$PREFIX" CF="$CFLAGS -I." LFLAGS1="$LDFLAGS" NOASM=1 USE_POSIX=1 
C -c -DUNIX -DFORCE_UNIX_OVER_WIN32  -Wall -DIZ_CRCOPTIM_UNFOLDTBL  -o unzip.o  -O2 -mcpu=pentiumpro unzip.c
process_begin: CreateProcess(NULL, C -c -DUNIX -DFORCE_UNIX_OVER_WIN32 -Wall -DIZ_CRCOPTIM_UNFOLDTBL -o unzip.o -O2 -mcpu=pentiumpro unzip.c, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [win32/Makefile.gcc:294: unzip.o] Error 2
```

I'm out of ideas for now.

**Pull request closed without merging**
