### PR TITLE
Pass -DNO_LCHMOD and install all targets

### LINKED ISSUE #9: zipinfo
Hi,

I am packaging https://github.com/GNOME/libgsf for conda-forge, and its tests use the `zipinfo` command [1] available with `unzip`. However, it looks like `zipinfo` is not available for the conda-forge's `unzip` package.

Could you please let me know why?

Best regards,
Sebastian

[1] https://github.com/GNOME/libgsf/blob/master/tests/LibGsfTest.pm#L24

### PR DESCRIPTION
**Pull request by chrisburr**
When unzipping files containing symlinks the current build prints lots of errors like:
```
lchmod (file attributes) error: Function not implemented
```
Most Linux distributions compile unzip with `-DNO_LCHMOD` to avoid this and I think conda-forge should do the same.

Also fixes #9 

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender.

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@conda-forge/unzip Ready for review (the linter was happy until I unmarked as a draft so it can be ignored)

**Comment by chrisburr** [comment]
@conda-forge-admin, please lint

**Comment by chrisburr** [comment]
@conda-forge/unzip Any thoughts?

**Comment by chrisburr** [comment]
@conda-forge/core, can somebody merge this please?

**Comment by isuruf** [comment]
Can you add yourself as a maintainer and bump the build number?

**Comment by chrisburr** [comment]
Well spotted @isuruf, not sure how I forgot....

**Pull request merged**
